// auto-generated header by CodeFromTemplate - Connected Vision - https://github.com/ConnectedVision
// CodeFromTemplate Version: 0.3 alpha
// stubs/Stub_Skeleton_ModuleDescription.h
// NEVER TOUCH this file!

#ifndef Stub_Skeleton_ModuleDescription_def
#define Stub_Skeleton_ModuleDescription_def

// --> Do NOT EDIT <--
namespace ConnectedVision {
namespace test {

/// module description
// --> Do NOT EDIT <--
static const char _moduleDescription[] =
	"{\n"
	"	\"name\": \"Skeleton Module\",\n"
	"	\"description\": \"\",\n"
	"	\"version\": 0.1,\n"
	"	\"moduleID\": \"Skeleton\",\n"
	"	\"moduleURI\": \"http://some.host/Skeleton\",\n"
	"	\"moduleLogoURI\": \"Skeleton.png\",\n"
	"	\"APIVersion\": 0.5,\n"
	"	\"moduleFeatures\": {\n"
	"		\"supportsLive\": true,\n"
	"		\"supportsResume\": true,\n"
	"		\"supportsDynamicParameters\": true\n"
	"	},\n"
	"	\"author\": \"???\",\n"
	"	\"params\": {\n"
	"		\"description\": \"Skeleton Dummy Parameter\",\n"
	"		\"required\": true,\n"
	"		\"type\": \"object\",\n"
	"		\"properties\": {\n"
	"			\"dummy\": {\n"
	"				\"description\": \"just a place holder\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"count\",\n"
	"				\"type\": \"integer\",\n"
	"				\"default\": 0\n"
	"			},\n"
	"			\"dummy_dynamic_parameter\": {\n"
	"				\"description\": \"just a place holder for a dynamic parameter\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"count\",\n"
	"				\"type\": \"integer\",\n"
	"				\"default\": 0,\n"
	"				\"dynamic\": true\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"}";

/// input description
// --> Do NOT EDIT <--
static const char _inputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"image source (PNG)\",\n"
	"		\"id\": \"PNG-Image\",\n"
	"		\"description\": \"\",\n"
	"		\"type\": \"image/png\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Detections\",\n"
	"		\"id\": \"Detections\",\n"
	"		\"description\": \"bounding box\",\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"objectID\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"first detection\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"boundingBox\": {\n"
	"				\"description\": \"bounding box\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"rectangle\",\n"
	"				\"properties\": {\n"
	"					\"left\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"x position of top left point of the rectangle\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"right\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"x position of bottom right point of the rectangle\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"top\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"y position of top left point of the rectangle\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"bottom\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"y position of bottom right point of the rectangle\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"required\": true\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"]";

/// output description
// --> Do NOT EDIT <--
static const char _outputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"Average\",\n"
	"		\"id\": \"Average\",\n"
	"		\"description\": \"This is a completely senseless output pin providing the average color of the area in the bounding box.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"first detection\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"color\": {\n"
	"				\"description\": \"average color of bounding box\",\n"
	"				\"unit\": \"\",\n"
	"				\"type\": \"object\",\n"
	"				\"properties\": {\n"
	"					\"R\": {\n"
	"						\"description\": \"red\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"color intensity 0-255\",\n"
	"						\"type\": \"integer\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"G\": {\n"
	"						\"description\": \"green\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"color intensity 0-255\",\n"
	"						\"type\": \"integer\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"B\": {\n"
	"						\"description\": \"blue\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"color intensity 0-255\",\n"
	"						\"type\": \"integer\",\n"
	"						\"default\": 0\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"]";

} // namespace test
} // namespace ConnectedVision

#endif // Stub_Skeleton_ModuleDescription_def