// auto-generated header by CodeFromTemplate - Connected Vision - https://github.com/ConnectedVision
// CodeFromTemplate Version: 0.3 alpha
// stubs/Stub_DummyBoundingBoxes_ModuleDescription.h
// NEVER TOUCH this file!

#ifndef Stub_DummyBoundingBoxes_ModuleDescription_def
#define Stub_DummyBoundingBoxes_ModuleDescription_def

// --> Do NOT EDIT <--
namespace ConnectedVision {
namespace Module {
namespace DummyBoundingBoxes {

/// module description
// --> Do NOT EDIT <--
static const char _moduleDescription[] =
	"{\n"
	"	\"name\": \"DummyBoundingBoxes\",\n"
	"	\"description\": \"This module generates dummy bounding boxes.\",\n"
	"	\"version\": 0.1,\n"
	"	\"moduleID\": \"DummyBoundingBoxes\",\n"
	"	\"moduleURI\": \"http://localhost:2020/DummyBoundingBoxes\",\n"
	"	\"moduleFeatures\": {\n"
	"		\"supportsLive\": false,\n"
	"		\"supportsResume\": false,\n"
	"		\"supportsDynamicParameters\": false\n"
	"	},\n"
	"	\"author\": \"Stephan Veigl\",\n"
	"	\"params\": {\n"
	"		\"description\": \"Dummy Bounding Box Generator configuration\",\n"
	"		\"required\": true,\n"
	"		\"type\": \"object\",\n"
	"		\"properties\": {\n"
	"			\"count\": {\n"
	"				\"description\": \"number of bounding boxes to be generated (interpolated)\",\n"
	"				\"type\": \"integer\",\n"
	"				\"unit\": \"count\",\n"
	"				\"required\": true,\n"
	"				\"default\": 0\n"
	"			},\n"
	"			\"boundingBoxStart\": {\n"
	"				\"description\": \"first bounding box data at start of video\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"rectangle\",\n"
	"				\"required\": true,\n"
	"				\"properties\": {\n"
	"					\"left\": {\n"
	"						\"description\": \"x position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"right\": {\n"
	"						\"description\": \"x position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"top\": {\n"
	"						\"description\": \"y position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"bottom\": {\n"
	"						\"description\": \"y position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					}\n"
	"				}\n"
	"			},\n"
	"			\"timestampStart\": {\n"
	"				\"description\": \"timestamp of first bounding box data at start of video\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"boundingBoxEnd\": {\n"
	"				\"description\": \"last bounding box data at end of video\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"rectangle\",\n"
	"				\"required\": true,\n"
	"				\"properties\": {\n"
	"					\"left\": {\n"
	"						\"description\": \"x position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"right\": {\n"
	"						\"description\": \"x position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"top\": {\n"
	"						\"description\": \"y position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"bottom\": {\n"
	"						\"description\": \"y position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					}\n"
	"				}\n"
	"			},\n"
	"			\"timestampEnd\": {\n"
	"				\"description\": \"timestamp of last bounding box data at end of video\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"delay\": {\n"
	"				\"description\": \"processing delay\",\n"
	"				\"type\": \"integer\",\n"
	"				\"unit\": \"ms\",\n"
	"				\"required\": false,\n"
	"				\"default\": 0\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"}";

/// input description
// --> Do NOT EDIT <--
static const char _inputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"Trigger\",\n"
	"		\"id\": \"Trigger\",\n"
	"		\"description\": \"Trigger pulse used as signal for the generation of a bounding box.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"application/json\",\n"
	"		\"minPinCount\": 0,\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"ms\"\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"]";

/// output description
// --> Do NOT EDIT <--
static const char _outputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"Detections\",\n"
	"		\"id\": \"Detections\",\n"
	"		\"description\": \"bounding box\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"configID\": {\n"
	"				\"description\": \"ID of config chain\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"id\": {\n"
	"				\"description\": \"detection ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"objectID\": {\n"
	"				\"description\": \"object ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"unit\": \"md5\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"boundingBox\": {\n"
	"				\"description\": \"bounding box\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"rectangle\",\n"
	"				\"required\": true,\n"
	"				\"properties\": {\n"
	"					\"left\": {\n"
	"						\"description\": \"x position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"right\": {\n"
	"						\"description\": \"x position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"top\": {\n"
	"						\"description\": \"y position of top left point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"bottom\": {\n"
	"						\"description\": \"y position of bottom right point of the rectangle\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					}\n"
	"				}\n"
	"			},\n"
	"			\"basePoint\": {\n"
	"				\"description\": \"base point\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"point\",\n"
	"				\"required\": true,\n"
	"				\"properties\": {\n"
	"					\"x\": {\n"
	"						\"description\": \"x position of point\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					},\n"
	"					\"y\": {\n"
	"						\"description\": \"y position of point\",\n"
	"						\"type\": \"number\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"required\": true,\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"ObjectData\",\n"
	"		\"id\": \"ObjectData\",\n"
	"		\"description\": \"object meta data\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"configID\": {\n"
	"				\"description\": \"ID of config chain\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"id\": {\n"
	"				\"description\": \"object ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"objectID\": {\n"
	"				\"description\": \"object ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"unit\": \"md5\",\n"
	"				\"required\": true\n"
	"			},\n"
	"			\"detections\": {\n"
	"				\"description\": \"list of detections of event\",\n"
	"				\"type\": \"array\",\n"
	"				\"required\": true,\n"
	"				\"items\": {\n"
	"					\"description\": \"detection\",\n"
	"					\"type\": \"object\",\n"
	"					\"required\": true,\n"
	"					\"properties\": {\n"
	"						\"timestamp\": {\n"
	"							\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"							\"type\": \"integer\",\n"
	"							\"exttype\": \"timestamp\",\n"
	"							\"unit\": \"ms\",\n"
	"							\"required\": true\n"
	"						},\n"
	"						\"confidence\": {\n"
	"							\"description\": \"confidence of detection [0-1]\",\n"
	"							\"type\": \"number\",\n"
	"							\"unit\": \"percentage\",\n"
	"							\"required\": false,\n"
	"							\"default\": 1,\n"
	"							\"minimum\": 0,\n"
	"							\"maximum\": 1\n"
	"						},\n"
	"						\"boundingBox\": {\n"
	"							\"description\": \"bounding box\",\n"
	"							\"type\": \"object\",\n"
	"							\"exttype\": \"rectangle\",\n"
	"							\"required\": true,\n"
	"							\"properties\": {\n"
	"								\"left\": {\n"
	"									\"description\": \"x position of top left point of the rectangle\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								},\n"
	"								\"right\": {\n"
	"									\"description\": \"x position of bottom right point of the rectangle\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								},\n"
	"								\"top\": {\n"
	"									\"description\": \"y position of top left point of the rectangle\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								},\n"
	"								\"bottom\": {\n"
	"									\"description\": \"y position of bottom right point of the rectangle\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								}\n"
	"							}\n"
	"						},\n"
	"						\"basePoint\": {\n"
	"							\"description\": \"base point\",\n"
	"							\"type\": \"object\",\n"
	"							\"exttype\": \"point\",\n"
	"							\"required\": true,\n"
	"							\"properties\": {\n"
	"								\"x\": {\n"
	"									\"description\": \"x position of point\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								},\n"
	"								\"y\": {\n"
	"									\"description\": \"y position of point\",\n"
	"									\"type\": \"number\",\n"
	"									\"unit\": \"fractional position\",\n"
	"									\"required\": true,\n"
	"									\"minimum\": 0,\n"
	"									\"maximum\": 1\n"
	"								}\n"
	"							}\n"
	"						}\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"]";

} // namespace DummyBoundingBoxes
} // namespace Module
} // namespace ConnectedVision

#endif // Stub_DummyBoundingBoxes_ModuleDescription_def