= HowTo: Custom OutputPin with OutputPin_Generic

[[summary]]
== Summary

Output Pins for custom data classes can easily be generated by deriving from the OutputPin_Generic template.

You just have to provide two functions to pack / encode / marshal / … your custom data to be transferred via a Connected Vision request (basically a HTTP request). All the other data handling (analyze the request, querying the data from the store, transfer the data, …) is done by the base classes.

[[requirements]]
== Requirements

* Custom data must be stored in an `IStore<TDataClass>` compatible container (e.g. Store_SQLite, Store_Ringbuffer, …)
* Stores must be managed by an `IStore_Manager<TDataClass>`

*Note:*

If the custom data store is derived from a provided store template, the store requires the custom data class to provide the following functions:

[source,C/C++]
....
const id_t& getconst_id();
void set_id(id_t value);
const timestamp_t& getconst_timestamp();
void set_timestamp(timestamp_t value;
const id_t& getconst_configID();
void set_configID(id_t value);
void clear();
....

[[implementation]]
== Implementation

[[declare-custom-output-pin-class]]
=== Declare Custom Output Pin Class

Derive your custom output pin from the OutputPin_Generic template class and instantiate the data class template parameter with your custom data class.

[source,C/C++]
....
class OutputPin_CustomData : public OutputPin_Generic<CustomDataClass>
....

The OutputPin_Generic template is located in: +
....
<ConnectedVision_root>\Cpp\src\ConnectedVision\common\OutputPins
....

*Optional:*

Add custom variables to constructor.

[source,C/C++]
....
/**
* constructor
*/
OutputPin_CustomData (
    ConnectedVision::shared_ptr< ConnectedVision::DataHandling::IStore_Manager<CustomDataClass> > dataStoreManager ///< [in] data store manager
    ConnectedVision::Module::MyModule::Foo foo ///< [in] additional parameter for custom output pin
);
....

[[set-outputpin-id]]
=== Set OutputPin ID

Implement the helper functions to provide the Pin ID.

[source,C/C++]
....
static const pinID_t PinID() \{ return "OutputPin_CustomData"; };
static const bool hasPinID( pinID_t id ) \{ return ( id === PinID() ); };
....

[[implement-pack-functions]]
=== Implement Pack Functions

You need to supply two functions to pack your custom data and write them to the Connected Vision response object.

The two functions are basically the same, the only difference is, that the `packSingleObject()` function is used when only a single data object should be sent, and the `packMultipleObjects()` function is used when multiple objects should be sent in a single request.

[source,C/C++]
....
/**
* encodes actual data and writes them to response
* @return status code (analog to HTTP codes)
*/
virtual ConnectedVision::HTTP::EnumHTTPStatus packSingleObject(
    const ConnectedVision::shared_ptr<const CustomDataClass> &obj, ///< [in] requested data object
    ConnectedVisionResponse &response ///< [out] reference to the ConnectedVisionResponse - results are written into this response
);

/**
* encodes actual data and writes them to @ref response
* @return status code (analog to HTTP codes)
*/
virtual ConnectedVision::HTTP::EnumHTTPStatus packMultipleObjects(
    const std::vector<const ConnectedVision::shared_ptr<const CustomDataClass>> &objs, ///< [in] requested data object
    ConnectedVisionResponse &response ///< [out] reference to the ConnectedVisionResponse - results are written into this response
);
....

The *pack functions* have to set:

* response content type (MIME type)
* response content with the encoded and packed custom data

[source,C/C++]
....
// set content type
response.setContentType("application/xyz");
// encode to string
response.setContent( obj->toStr() );
....

In case of an *error*, the functions should write an error message to the response object. This can be done by the `writeErrorResponse()` helper function.

[source,C/C++]
....
// no data found
writeErrorResponse(response, ConnectedVision::HTTP::HTTP_Status_NOT_FOUND, PinID(), "not found");
....

*If there is no way to transfer multiple objects* within one request (e.g. images), a common solution is to return the *first object* (and in most cases the only). In this case the `packMultipleObjects()` function will simply call the `packSingleObject()` function (after some error checking).

[source,C/C++]
....
virtual ConnectedVision::HTTP::EnumHTTPStatus packMultipleObjects(
    const std::vector<const ConnectedVision::shared_ptr<const CustomDataClass>> &objs,
    ConnectedVisionResponse &response )
{
    if ( !objs.size() )
    {
        // not found
        return writeErrorResponse(response, ConnectedVision::HTTP::HTTP_Status_NOT_FOUND, PinID(), "not found");
    }
    return this->packSingleObject(objs.at(0), response);
}
....

[[example]]
== Example

TODO