// auto-generated header by CodeFromTemplate - Connected Vision - https://github.com/ConnectedVision
// CodeFromTemplate Version: 0.3 alpha
// stubs/Stub_SyntheticVideo_ModuleDescription.h
// NEVER TOUCH this file!

#ifndef Stub_SyntheticVideo_ModuleDescription_def
#define Stub_SyntheticVideo_ModuleDescription_def

// --> Do NOT EDIT <--
namespace ConnectedVision {
namespace Module {
namespace SyntheticVideo {

/// module description
// --> Do NOT EDIT <--
static const char _moduleDescription[] =
	"{\n"
	"	\"name\": \"SyntheticVideo\",\n"
	"	\"description\": \"This module produces synthetic video frames as well as synthetic video meta data. It has 2 metadata output pins and 3 raw frame output pins and a png output pin.\",\n"
	"	\"version\": 0.1,\n"
	"	\"moduleID\": \"SyntheticVideo\",\n"
	"	\"moduleURI\": \"\",\n"
	"	\"moduleLogoURI\": \"SyntheticVideo.png\",\n"
	"	\"author\": \"Connected Vision\",\n"
	"	\"params\": {\n"
	"		\"type\": \"object\",\n"
	"		\"properties\": {\n"
	"			\"recordingDateTime\": {\n"
	"				\"description\": \"recording date (start time of video)\",\n"
	"				\"required\": false,\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\",\n"
	"				\"default\": 0\n"
	"			},\n"
	"			\"numberOfFrames\": {\n"
	"				\"description\": \"number of frames in synthetic video\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"\",\n"
	"				\"type\": \"number\"\n"
	"			},\n"
	"			\"height\": {\n"
	"				\"description\": \"height of frames\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"number\"\n"
	"			},\n"
	"			\"width\": {\n"
	"				\"description\": \"width of frames\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"number\"\n"
	"			},\n"
	"			\"fps\": {\n"
	"				\"description\": \"number of frames per second\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"frames/sec\",\n"
	"				\"type\": \"number\"\n"
	"			},\n"
	"			\"sizeOfObject\": {\n"
	"				\"description\": \"size of object in synthetic video\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"number\"\n"
	"			},\n"
	"			\"bgColor\": {\n"
	"				\"description\": \"background color\",\n"
	"				\"unit\": \"RGB value\",\n"
	"				\"type\": \"object\",\n"
	"				\"properties\": {\n"
	"					\"R\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"R value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"G\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"G value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"B\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"B value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					}\n"
	"				}\n"
	"			},\n"
	"			\"fgColor\": {\n"
	"				\"description\": \"foreground color\",\n"
	"				\"unit\": \"RGB value\",\n"
	"				\"type\": \"object\",\n"
	"				\"properties\": {\n"
	"					\"R\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"R value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"G\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"G value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"B\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"B value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					}\n"
	"				}\n"
	"			},\n"
	"			\"osdTextColor\": {\n"
	"				\"description\": \"OSD text color\",\n"
	"				\"unit\": \"RGB value\",\n"
	"				\"type\": \"object\",\n"
	"				\"properties\": {\n"
	"					\"R\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"R value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"G\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"G value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					},\n"
	"					\"B\": {\n"
	"						\"description\": \"\",\n"
	"						\"required\": true,\n"
	"						\"unit\": \"B value\",\n"
	"						\"type\": \"number\",\n"
	"						\"default\": 0\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"}";

/// input description
// --> Do NOT EDIT <--
static const char _inputPinDescription[] =
	"[]";

/// output description
// --> Do NOT EDIT <--
static const char _outputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"Synthetic Video Metadata\",\n"
	"		\"id\": \"VideoMetadata\",\n"
	"		\"description\": \"synthetic video meta data\",\n"
	"		\"static\": true,\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"Object ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"job / config ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"filename\": {\n"
	"				\"description\": \"filename\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"location of avi file\",\n"
	"				\"type\": \"string\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"start time\",\n"
	"				\"required\": true,\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"lasttimestamp\": {\n"
	"				\"description\": \"end time\",\n"
	"				\"required\": true,\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"width\": {\n"
	"				\"description\": \"width of video in pixels\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"integer\"\n"
	"			},\n"
	"			\"height\": {\n"
	"				\"description\": \"height of video in pixels\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"integer\"\n"
	"			},\n"
	"			\"numberofframes\": {\n"
	"				\"description\": \"number of frames in video\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"\",\n"
	"				\"type\": \"integer\"\n"
	"			},\n"
	"			\"fps\": {\n"
	"				\"description\": \"number of frames per second\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"frames/sec\",\n"
	"				\"type\": \"number\"\n"
	"			}\n"
	"		}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Synthetic Frame Metadata\",\n"
	"		\"id\": \"FrameMetadata\",\n"
	"		\"description\": \"synthetic frame meta data\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"application/json\",\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"Object ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"job / config ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"description\": \"start time\",\n"
	"				\"required\": true,\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"framenumber\": {\n"
	"				\"description\": \"frame number\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"\",\n"
	"				\"type\": \"integer\"\n"
	"			},\n"
	"			\"width\": {\n"
	"				\"description\": \"width of frame in pixels\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"integer\"\n"
	"			},\n"
	"			\"height\": {\n"
	"				\"description\": \"height of frame in pixels\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"pixel\",\n"
	"				\"type\": \"integer\"\n"
	"			}\n"
	"		}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"RAW YUV420 Image\",\n"
	"		\"id\": \"RAWYUV420-Image\",\n"
	"		\"description\": \"yuv420 binary image data\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/rawyuv420\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"RAW BGR24 Image\",\n"
	"		\"id\": \"RAWBGR24-Image\",\n"
	"		\"description\": \"bgr24 binary image data\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/rawbgr24\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"RAW RGB24 Image\",\n"
	"		\"id\": \"RAWRGB24-Image\",\n"
	"		\"description\": \"rgb24 binary image data\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/rawrgb24\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"PNG Image\",\n"
	"		\"id\": \"PNG-Image\",\n"
	"		\"description\": \"png image\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/png\",\n"
	"		\"properties\": {}\n"
	"	}\n"
	"]";

} // namespace SyntheticVideo
} // namespace Module
} // namespace ConnectedVision

#endif // Stub_SyntheticVideo_ModuleDescription_def