// auto-generated header by CodeFromTemplate - Connected Vision - https://github.com/ConnectedVision
// CodeFromTemplate Version: 0.3 alpha
// stubs/Stub_ThumbnailGenerator_ModuleDescription.h
// NEVER TOUCH this file!

#ifndef Stub_ThumbnailGenerator_ModuleDescription_def
#define Stub_ThumbnailGenerator_ModuleDescription_def

// --> Do NOT EDIT <--
namespace ConnectedVision {
namespace Module {
namespace ThumbnailGenerator {

/// module description
// --> Do NOT EDIT <--
static const char _moduleDescription[] =
	"{\n"
	"	\"name\": \"Thumbnail Generator\",\n"
	"	\"description\": \"This module provides image manipulation functions. 1.: It can crop the input image according to the defined rectangular region. 2.: It can overlay the input image with bounding boxes.\",\n"
	"	\"version\": 0.2,\n"
	"	\"moduleID\": \"ThumbnailGenerator\",\n"
	"	\"moduleURI\": \"\",\n"
	"	\"moduleLogoURI\": \"ThumbnailGenerator.png\",\n"
	"	\"author\": \"Stephan Veigl\",\n"
	"	\"params\": {\n"
	"		\"type\": \"object\",\n"
	"		\"required\": true,\n"
	"		\"properties\": {\n"
	"			\"imageFormat\": {\n"
	"				\"type\": \"string\",\n"
	"				\"description\": \"image format\",\n"
	"				\"enum\": [\n"
	"					\"JPEG\",\n"
	"					\"PNG\"\n"
	"				],\n"
	"				\"required\": false,\n"
	"				\"default\": \"JPEG\"\n"
	"			},\n"
	"			\"lineWidth\": {\n"
	"				\"type\": \"integer\",\n"
	"				\"description\": \"line width\",\n"
	"				\"unit\": \"pixel\",\n"
	"				\"default\": 3,\n"
	"				\"required\": false\n"
	"			},\n"
	"			\"lineColor\": {\n"
	"				\"description\": \"line color\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"color\",\n"
	"				\"required\": false,\n"
	"				\"properties\": {\n"
	"					\"R\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"red component\",\n"
	"						\"unit\": \"normalized value\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 0,\n"
	"						\"required\": false\n"
	"					},\n"
	"					\"G\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"green component\",\n"
	"						\"unit\": \"normalized value\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 0,\n"
	"						\"required\": false\n"
	"					},\n"
	"					\"B\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"blue component\",\n"
	"						\"unit\": \"normalized value\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 0,\n"
	"						\"required\": false\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"}";

/// input description
// --> Do NOT EDIT <--
static const char _inputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"PNG Image\",\n"
	"		\"id\": \"PNG-Image\",\n"
	"		\"description\": \"image data encoded as PNG\",\n"
	"		\"type\": \"image/png\",\n"
	"		\"static\": false,\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Image Metadata\",\n"
	"		\"id\": \"ImageMetadata\",\n"
	"		\"description\": \"image metadata\",\n"
	"		\"type\": \"application/json\",\n"
	"		\"static\": false,\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"job / config ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"ms\"\n"
	"			}\n"
	"		}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Bounding Box\",\n"
	"		\"id\": \"BoundingBox\",\n"
	"		\"description\": \"rectangular region which is used for the cropping or for overlaying bounding boxes\",\n"
	"		\"type\": \"application/json\",\n"
	"		\"static\": false,\n"
	"		\"properties\": {\n"
	"			\"id\": {\n"
	"				\"description\": \"ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"configID\": {\n"
	"				\"description\": \"job / config ID\",\n"
	"				\"type\": \"string\",\n"
	"				\"exttype\": \"id\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"md5\"\n"
	"			},\n"
	"			\"timestamp\": {\n"
	"				\"type\": \"integer\",\n"
	"				\"exttype\": \"timestamp\",\n"
	"				\"description\": \"timestamp in milliseconds since 1970-01-01 00:00:00.000 UTC\",\n"
	"				\"required\": true,\n"
	"				\"unit\": \"ms\"\n"
	"			},\n"
	"			\"boundingBox\": {\n"
	"				\"description\": \"bounding box\",\n"
	"				\"type\": \"object\",\n"
	"				\"exttype\": \"rectangle\",\n"
	"				\"required\": true,\n"
	"				\"properties\": {\n"
	"					\"left\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"x position of left side\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 0,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"right\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"x position of right side\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 1,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"bottom\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"y position of bottom side\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 1,\n"
	"						\"required\": true\n"
	"					},\n"
	"					\"top\": {\n"
	"						\"type\": \"number\",\n"
	"						\"description\": \"y position of top side\",\n"
	"						\"unit\": \"fractional position\",\n"
	"						\"minimum\": 0,\n"
	"						\"maximum\": 1,\n"
	"						\"default\": 0,\n"
	"						\"required\": true\n"
	"					}\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"]";

/// output description
// --> Do NOT EDIT <--
static const char _outputPinDescription[] =
	"[\n"
	"	{\n"
	"		\"name\": \"Bounding Box Overlay\",\n"
	"		\"id\": \"BoundingBoxOverlay\",\n"
	"		\"description\": \"The input image with overlayed bounding boxes. The data is indexed by the IDs, indices and timestamps of the images.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/jpeg\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Bounding Box Overlay Thumbnail\",\n"
	"		\"id\": \"BoundingBoxOverlayThumbnail\",\n"
	"		\"description\": \"The input image thumbnail with overlayed bounding boxes. The data is indexed by the IDs, indices and timestamps of the images.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/jpeg\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Cropped Image\",\n"
	"		\"id\": \"CroppedImage\",\n"
	"		\"description\": \"The cropped image. The data is indexed by the IDs, indices and timestamps of the bounding boxes.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/jpeg\",\n"
	"		\"properties\": {}\n"
	"	},\n"
	"	{\n"
	"		\"name\": \"Cropped Image Thumbnail\",\n"
	"		\"id\": \"CroppedImageThumbnail\",\n"
	"		\"description\": \"The cropped image thumbnail. The data is indexed by the IDs, indices and timestamps of the bounding boxes.\",\n"
	"		\"static\": false,\n"
	"		\"type\": \"image/jpeg\",\n"
	"		\"properties\": {}\n"
	"	}\n"
	"]";

} // namespace ThumbnailGenerator
} // namespace Module
} // namespace ConnectedVision

#endif // Stub_ThumbnailGenerator_ModuleDescription_def